export const HOME_HEADER = "HOME_HEADER";
export const HOME_THREE_COLUMNS = "HOME_THREE_COLUMNS";
export const HOME_FOUR_STEPS = "HOME_FOUR_STEPS";
export const HOME_ABOUT_US = "HOME_ABOUT_US";
export const HOME_INSTITUTIONS = "HOME_INSTITUTIONS";
export const HOME_CONTACT = "HOME_CONTACT";
